### ISSUE TITLE
Remove T2w processing in processing pipeline

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#50]
## Context
With the segmentation results from the first 350 subjects, we decided to only use T1w images for the project:
* Subjects to correct segmentation
    * T1w: 15/350
    * T2w: 50/350
* Subjects to exclude→ 47 / 700 from QC report
    * T1w : 6/350
    * T2w : 41/350

This implicates that the processing pipeline needs to be adjusted to only generate sc segmentations and vertebral lableing for T1w images (mainly in process_data.sh) .
## Tasks
The removal of T2w images implicates the following changes:
- [x] Remove T2w processing from `process_data.sh`
- [x] Adapt `compute_stats.py` to remove T2w from the statistical models
- [x] Adjust `README.md` mainly [Data collection and organization](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa#data-collection-and-organization)
