### ISSUE TITLE
Add PMJ detection in processing pipeline

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#78]
## Context
To measure CSA based on distance from pontomedullary junction (PMJ) (see this [PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3429)), we have to first detect PMJ in the processing pipeline.

## TODO

- [x] Add detection of PMJ in `process_data.sh` using `sct_detect_pmj`
- [x] Add use of `sct_process_segementation` with the flag `-pmj` on the branch `jca/sb/3063-csa-measure-from-pmj` in spinalcordtoolbox
- [x] Add possibilty to use manual label of PMJ
