### ISSUE TITLE
Add manual labeling of PMJ label in `manual_correction.py`

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#80]
## Context
Since we are now also computing CSA based on the distance from PMJ, we need the PMJ label. `sct_detect_pmj` can fail, we need to add  the option to manually label PMJ to the script `manual_correction.py`

## TODO
- [x] Add function to call `sct_label_utils -create-viewer 50` 
- [x]  Choose a name for derivative: could be: `sub-XXX_T1w_pmj-manual.nii.gz` .
- [x] Update README to add instructions to manually label PMJ.
