### ISSUE TITLE
Add scatterplot of PMJ-based CSA vs C2-C3-based CSA in `compute_stats.py`

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#84]
## TODO

- [x] Add PMJ-based CSA in `get_subject_info`
- [x] Add scatterplot of PMJ-based CSA vs C2-C3-based CSA in `compute_stats.py`
- [x] Add scatterplot of distance between C2-C3 disc and PMJ (related to #83 ) in `compute_stats.py`
- [x] Use PMJ-based CSA for statistics + normalization
